version: 0.2

# aws codebuild start-build --project-name developers-paradise-arm
# aws logs tail  developers-paradise --follow
# aws codebuild batch-get-build  --ids developers-paradise:84668fdd-9e44-4911-b478-852691365680
# aws cloudformation deploy  --template-file .github/workflows/gh-aws-iam.cloudformation --stack-name gh-iam-developers-paradise  --capabilities CAPABILITY_NAMED_IAM
# streamname

env:
  #variables:
  #  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  secrets-manager:
    NECKLESS_PRIVKEY: "arn:aws:secretsmanager:eu-central-1:973800055156:secret:developers-paradise/neckless-PzSfaq:developers-paradise"
#  parakmeter-store:

phases:
  install:
    commands:
      #docker run -v /run/docker.sock:/run/docker.sock -e GITHUB_ACCESS_TOKEN=xxxxxxxx -e RUNNER_LABELS=foo -e RUNNER_REPOSITORY_URL=https://github.com/mabels/developers-paradise -ti public.ecr.aws/mabels/developers-paradise:ghrunner-x86_64-a88149a-61f02921 su runner -c "cd /home/runner/actions-runner &&  /home/runner/actions-runner/start-worker.sh ./run.sh --ephemeral"
      - mkdir -p /var/lib/containers/storage
      - rsync -vaxH /var/lib/containers/storage . 
      - rm -rf /var/lib/containers/storage/
      - mkdir -p /var/lib/containers/storage
      - mount --bind storage /var/lib/containers/storage 
      - uname -a
      - curl -Lo /tmp/neckless.tar.gz https://github.com/mabels/neckless/releases/download/v0.1.9/neckless_0.1.9_Linux_$(uname -m | sed 's/aarch64/arm64/').tar.gz
      - tar xvzCf /usr/local/bin /tmp/neckless.tar.gz neckless
      - AWS_ACCESS_KEY_ID=$(neckless kv ls AWS_ACCESS_KEY_ID --onlyValue) AWS_SECRET_ACCESS_KEY=$(neckless kv ls AWS_SECRET_ACCESS_KEY --onlyValue) aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - APIUSER=$(neckless kv ls APIUSER --onlyValue) make all REPO=public.ecr.aws/d3g6c8d4 DOCKER=docker
      - APIUSER=$(neckless kv ls APIUSER --onlyValue) make push REPO=public.ecr.aws/d3g6c8d4 DOCKER=docker


#      - neckless kv ls
#      - env | grep NECK | base64
#      - docker ps || echo "no docker"
#      - neckless version || echo "no neckless"
#      - env | grep AWS
