version: 0.2

#env:
  #variables:
  #  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  #parameter-store:
  #  LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - make all REPO=public.ecr.aws/d3g6c8d4

#   finally:
#     - echo This always runs even if the update or install command fails 

