version: 0.2

env:
  #variables:
  #  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  secrets-manager:
    NECKLESS_PRIVKEY: "arn:aws:secretsmanager:eu-central-1:167250265666:secret:developer-paradise/neckless/privkey-BxWSH6"
#  parameter-store:

phases:
  install:
    commands:
      - export NVM_DIR="/usr/local/nvm"
      - . "$NVM_DIR/nvm.sh"
      - nvm use lts/gallium
      - eval $(neckless kv ls --ghAddMask  --shKeyValue APIUSER AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY)
      - env
      - make all REPO=public.ecr.aws/d3g6c8d4

